version: '3'
services:
  dify-sso:  
    # image: lework/dify-sso
    build: .
    container_name: dify-sso
    restart: always
    volumes:
      - ./app:/app/app
      - ~/administrator_project/dify/docker/volumes/app/storage:/app/api/storage
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - docker_default

networks:
  docker_default:       
    external: true